FROM almalinux:9
RUN dnf install nginx -y # Install nginx web server at build time
EXPOSE 8080  # Expose port 8080 for HTTP traffic
CMD ["nginx", "-g", "daemon off;"] # Start nginx in the foreground # it was to keep the container running 