FROM almalinux:9
RUN dnf install nginx -y
RUN -rm -f /usr/share/nginx/html/index.html
#this instruction is run when someone uses this image as base image
ONBUILD copy index.html /usr/share/nginx/html/index.html
CMD ["nginx", "-g", "daemon off;"]